server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由功能，利用微服务名进行路由
      routes:
        - id: payment_routh # 路由Id，没有固定规则蛋要求唯一，建议配合服务名
          #uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/** # 断言，路径想匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
#            - Before=2022-10-20T15:03:59.394+08:00[Asia/Shanghai]
#            - Cookie=username,YaoWenJun
#            - Header=X-Request-id,\d+
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    # 是否将自身注入注册表
    register-with-eureka: true
    # 获取注册表信息
    fetch-registry: true
    # 默认eureka地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/