server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false
#feign:
#  client:
#    config:
#      default:
#        ConnectTimeOut: 5000
#        ReadTimeOut: 5000
# 配置日志监控地址
logging:
  level:
    com.ywj.springcloud.service.PaymentFeignService: debug
